services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Bucharest/Europe
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - PUID=0
      - PGID=0
    volumes:
      - ./appdata:/config
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
