services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Bucharest
    ports:
      - 5055:5055
    volumes:
      - ./overseer/:/app/config
    restart: unless-stopped
